services:
  # 1. Start the Backend API (Python)
  - type: web
    name: electromatics-api
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
    autoDeploy: true

  # 2. Start the Frontend Website (Static HTML/JS)
  - type: web
    name: electromatics-web
    env: static
    rootDir: .
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

databases:
  # 3. Create a Database (PostgreSQL)
  - name: electromatics-db
    plan: free
    region: oregon
